import { Router } from 'express';
import { apiLimiter } from '../middleware/rateLimiter.js';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import departmentRoutes from './department.routes.js';
import categoryRoutes from './category.routes.js';
import unitRoutes from './unit.routes.js';
import productRoutes from './product.routes.js';
import supplierRoutes from './supplier.routes.js';
import stockTransactionRoutes from './stockTransaction.routes.js';
import stockBalanceRoutes from './stockBalance.routes.js';
import stockLedgerRoutes from './stockLedger.routes.js';
import reportRoutes from './report.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import roleRoutes from './role.routes.js';
import stockBatchRoutes from './stockBatch.routes.js';
import assetRoutes from './asset.routes.js';
import borrowGroupRoutes from './borrowGroup.routes.js';
import donationRoutes from './donation.routes.js';
import donationOccasionRoutes from './donationOccasion.routes.js';
import assetTransactionRoutes from './assetTransaction.routes.js';
import assetReportRoutes from './assetReport.routes.js';
import settingsRoutes from './settings.routes.js';
import supplierPaymentRoutes from './supplierPayment.routes.js';
import paymentTemplateRoutes from './paymentTemplate.routes.js';
import auditLogRoutes from './auditLog.routes.js';
import purchaseEntryRoutes from './purchaseEntry.routes.js';

const router = Router();

router.use(apiLimiter);

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/departments', departmentRoutes);
router.use('/categories', categoryRoutes);
router.use('/units', unitRoutes);
router.use('/products', productRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/transactions', stockTransactionRoutes);
router.use('/balances', stockBalanceRoutes);
router.use('/ledger', stockLedgerRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/roles', roleRoutes);
router.use('/batches', stockBatchRoutes);
router.use('/assets', assetRoutes);
router.use('/borrow-groups', borrowGroupRoutes);
router.use('/donations', donationRoutes);
router.use('/donation-occasions', donationOccasionRoutes);
router.use('/asset-transactions', assetTransactionRoutes);
router.use('/asset-reports', assetReportRoutes);
router.use('/settings', settingsRoutes);
router.use('/supplier-payments',   supplierPaymentRoutes);
router.use('/payment-templates',   paymentTemplateRoutes);
router.use('/audit-logs',          auditLogRoutes);
router.use('/purchase-entries',    purchaseEntryRoutes);

export default router;
