export const ROLE_PERMISSIONS = {
  super_admin: ['*'],
  admin: [
    'users:read', 'users:write', 'users:delete',
    'masters:read', 'masters:write', 'masters:delete',
    'transactions:read', 'transactions:create', 'transactions:delete',
    'reports:read',
    'assets:read', 'assets:write', 'assets:manage',
    'donations:read', 'donations:write',
    'payments:read', 'payments:write', 'payments:approve',
    'mahaprasad:read', 'mahaprasad:issue', 'mahaprasad:redeem',
  ],
  store_manager: [
    'masters:read', 'masters:write',
    'transactions:read', 'transactions:create', 'transactions:delete',
    'reports:read',
  ],
  staff: [
    'masters:read',
    'transactions:read', 'transactions:create',
    'reports:read',
    'assets:read',
    'donations:read',
    'payments:read', 'payments:write',
    'mahaprasad:read', 'mahaprasad:issue', 'mahaprasad:redeem',
  ],
  viewer: [
    'masters:read',
    'reports:read',
    'donations:read',
    'payments:read',
    'mahaprasad:read',
  ],
  mahaprasad_counter: ['mahaprasad:read', 'mahaprasad:issue'],
  mahaprasad_redeem:  ['mahaprasad:redeem'],
  donation_desk:      ['donations:read', 'donations:write'],
  accountant:         ['reports:read', 'transactions:read', 'donations:read', 'payments:read'],
  cashier:            ['payments:read', 'payments:write', 'payments:approve', 'reports:read'],
};

export const ROLE_LABELS = {
  super_admin:        'Super Admin',
  admin:              'Admin',
  store_manager:      'Store Manager',
  staff:              'Staff',
  viewer:             'Viewer',
  mahaprasad_counter: 'Mahaprasad Counter',
  mahaprasad_redeem:  'Mahaprasad Redeem',
  donation_desk:      'Donation Desk',
  accountant:         'Accountant',
  cashier:            'Cashier',
};
