export const rolesSeed = [
  {
    slug: 'super_admin',
    name: 'Super Admin',
    description: 'Full access to everything',
    permissions: ['*'],
    isSystem: true,
  },
  {
    slug: 'admin',
    name: 'Admin',
    description: 'Manage users, masters, transactions and reports',
    permissions: [
      'users:read', 'users:write', 'users:delete',
      'masters:read', 'masters:write', 'masters:delete',
      'transactions:read', 'transactions:create', 'transactions:delete',
      'reports:read',
      'assets:read', 'assets:write', 'assets:manage',
      'donations:read', 'donations:write',
      'payments:read', 'payments:write', 'payments:approve',
      'mahaprasad:read', 'mahaprasad:issue', 'mahaprasad:redeem',
    ],
    isSystem: true,
  },
  {
    slug: 'store_manager',
    name: 'Store Manager',
    description: 'Manage stock, masters and transactions',
    permissions: [
      'masters:read', 'masters:write',
      'transactions:read', 'transactions:create', 'transactions:delete',
      'reports:read',
    ],
    isSystem: true,
  },
  {
    slug: 'staff',
    name: 'Staff',
    description: 'Create transactions within assigned departments',
    permissions: [
      'masters:read',
      'transactions:read', 'transactions:create',
      'reports:read',
      'assets:read',
      'donations:read',
      'payments:read', 'payments:write',
      'mahaprasad:read', 'mahaprasad:issue', 'mahaprasad:redeem',
    ],
    isSystem: true,
  },
  {
    slug: 'viewer',
    name: 'Viewer',
    description: 'Read-only access to masters and reports',
    permissions: ['masters:read', 'reports:read', 'donations:read', 'payments:read', 'mahaprasad:read'],
    isSystem: true,
  },
  {
    slug: 'mahaprasad_counter',
    name: 'Mahaprasad Counter',
    description: 'Issue mahaprasad coupons at the counter',
    permissions: ['mahaprasad:read', 'mahaprasad:issue'],
    isSystem: true,
  },
  {
    slug: 'mahaprasad_redeem',
    name: 'Mahaprasad Redeem',
    description: 'Redeem mahaprasad coupons at the food counter',
    permissions: ['mahaprasad:redeem'],
    isSystem: true,
  },
  {
    slug: 'donation_desk',
    name: 'Donation Desk',
    description: 'Create and view donations',
    permissions: ['donations:read', 'donations:write'],
    isSystem: true,
  },
  {
    slug: 'accountant',
    name: 'Accountant',
    description: 'Read-only access to reports, transactions, donations and payments',
    permissions: ['reports:read', 'transactions:read', 'donations:read', 'payments:read'],
    isSystem: true,
  },
  {
    slug: 'cashier',
    name: 'Cashier',
    description: 'Manage and approve payments',
    permissions: ['payments:read', 'payments:write', 'payments:approve', 'reports:read'],
    isSystem: true,
  },
];
